name: ECharts Doc

on:
  workflow_dispatch:

jobs:
  run:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [12, 14, 16, 18]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout ECharts Doc Repo
        run: git clone --depth=1 https://github.com/apache/echarts-doc

      - name: Install Dependencies
        run: |
          cd echarts-doc
          npm i

      - name: Run dev
        run: npm run dev