name: ECharts Doc

on:
  workflow_dispatch:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout ECharts Doc Repo
        run: git clone --depth=1 https://github.com/apache/echarts-doc

      - name: Install Dependencies & Run dev
        run: |
          cd echarts-doc
          node -v
          npm -v
          npm i
          npm run dev