name: Update NOTICE year

on:
  schedule:
    - cron: '0 0 1 1 *'
  workflow_dispatch:

jobs:
  update-notice-year:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/workflows/.scripts

      - uses: actions/github-script@v7
        with:
          script: |
            const updateNoticeYear = require('.github/workflows/.scripts/update-notice-year.js')
            await updateNoticeYear({ octokit: github, context })




